### ISSUE TITLE
Add new atom type and failed when training

### ISSUE THREAD

**Issue by Auroraywood** [fimrie/DeepCoy#3]
Hi I'm found that your model atom dictionary doesn't have phosphorus, and I added it. but I didn't modify bucket_sizes, because I don't know what it does
```
    elif dataset=='zinc':
        return { 'atom_types': ['Br1(0)', 'C4(0)', 'Cl1(0)', 'F1(0)', 'H1(0)', 'I1(0)',
                'N2(-1)', 'N3(0)', 'N4(1)', 'O1(-1)', 'O2(0)', 'S2(0)','S4(0)', 'S6(0)', 'P5(0)'],
                 'maximum_valence': {0: 1, 1: 4, 2: 1, 3: 1, 4: 1, 5:1, 6:2, 7:3, 8:4, 9:1, 10:2, 11:2, 12:4, 13:6, 14:5},
                 'number_to_atom': {0: 'Br', 1: 'C', 2: 'Cl', 3: 'F', 4: 'H', 5:'I', 6:'N', 7:'N', 8:'N', 9:'O', 10:'O', 11:'S', 12:'S', 13:'S', 14:'P'},
                 'bucket_sizes': np.array([28,31,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,53,55,58,84]) 
               }
```

BUT failed when training. Is there anything else that needs to be modified?
Can you help me? Thanks!

**Comment by Auroraywood** [comment]
@fimrie

**Comment by fimrie** [comment]
Hi @Auroraywood and apologies for the delay in responding to your query. Please could you let me know the error message produced during training?

**Comment by jooewood** [comment]
Hi, @fimrie , Here is the error message, My previous account @Auroraywood has forgot email, so I create a new one:
```
Exception has occurred: AlreadyExistsError

Resource 
__per_step_3/gradients/while/add_11/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
	 [[{{node gradients/while/add_11/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var}}]]

During handling of the above exception, another exception occurred:

  File "/y/home/zdx/src/deepcoy/GGNN_DeepCoy.py", line 253, in run_epoch
    result = self.sess.run(fetch_list, feed_dict=batch_data)
  File "/y/home/zdx/src/deepcoy/GGNN_DeepCoy.py", line 285, in train
    self.train_data, True)
  File "/y/home/zdx/src/deepcoy/DeepCoy.py", line 1138, in <module>
    model.train()
```

**Comment by fimrie** [comment]
Hi @jooewood I was not able to replicate the error message that you posted. I have updated the repo to include a model atom dictionary that includes phosphorus. Instead of `--dataset zinc`, you should use `--dataset zinc_phosphorus` when training/generating using DeepCoy. In addition, molecules must be prepared using `zinc_phosphorus` rather than `zinc`. See the README in the `data` directory for more details. Hopefully this solves your issues.
