### ISSUE TITLE
Number of propertes problem

### ISSUE THREAD

**Issue by jooewood** [fimrie/DeepCoy#4]
Hi, 

In your article, you mentioned that you compute 27 unique properties.

But, in your script decoy_utils.py `calc_props_all` function, I only find 26 properties. I checked many times, seems like it is 26 properties.

Any suggestions? thanks!

**Comment by fimrie** [comment]
Hi,

Thank you for bringing this to our attention and our apologies for the delay in our reply.

We have confirmed that the 26 properties included in the function `calc_props_all` in the script `decoy_utils.py` are the properties we used to unbias and assess decoys in our article. These 26 properties precisely reproduce the reported results. The reference to 27 in our paper is a typographical error and should read 26. We apologize for any confusion this has caused.

**Comment by jooewood** [comment]
Thank you!
