### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'

### ISSUE THREAD

**Issue by sherifelsabbagh** [fimrie/DeepCoy#7]
I found this error when I tried to generate decoys

AttributeError: module 'tensorflow' has no attribute 'ConfigProto'

**Comment by fimrie** [comment]
Hi @sherifelsabbagh, please could you let me know what version of tensorflow you're using?

DeepCoy was tested with version 1.10 but should work for several other versions. My understanding is that ConfigProto was in tensorflow 2.0, so if you would like to use that version of tensorflow, you might need to adapt some of the code accordingly

**Comment by sherifelsabbagh** [comment]
Dear @fimrie Thanks for your reply. 

I did what you said and it worked. The code needed to be updated.
